### ISSUE TITLE
preparing 4.0.0 release still in progress any eta on this?

### ISSUE THREAD

**Issue by ramonskie** [bflad/chef-stash#123]
there is still teh notification of
```
We are preparing for 4.0.0 release which makes the git repo not stable for now. Please use cookbook from Supermarket for the time being.
```
i was wondering if you have any eta for this or do you need any help?

**Comment by linc01n** [comment]
Hi @ramonskie ,
I just moved to a new country in Aug. So I didn't have much time for the project. 
Now I'm almost settled and I'm starting to work on the project again.

I'm running different kind of test on the project. Since our 4.0 release will change the default database to postgres, I'm testing different upgrade scenarios. 

And at the same time Atlassian rename the project to bitbucket which create more problems. 
I've paused for a few weeks to wait for the 4.0.3 release which fixes [this](https://github.com/bflad/chef-stash/pull/116#issuecomment-146486577).

I've just found [this](https://github.com/bflad/chef-stash/blob/5cf434dc1a83242c42aad0eda738b5936d764e56/templates/default/bitbucket/setenv.sh.erb#L15) is causing problems when people choose to use openjdk or a different version of jdk.

Also in the `setenv.sh` they've removed `MaxPermSize` which caused issue in the past. #84 

Hopefully I can release our 4.0 cookbook this week.

When I'm upgrading from 3.10 to 4.1, I lost all my repos. It gives me a `You have an empty repository` message.

I need help to reproduce and fix this issue.

Thanks @ramonskie

**Comment by ramonskie** [comment]
i have not seen such issue
and i think you should not handle the migration from mysql to postgres in this cookbook
i think users should do this by just doing a export/import or use the database migration wizard
https://confluence.atlassian.com/bitbucketserver/connecting-bitbucket-server-to-an-external-database-776640378.html

**Comment by linc01n** [comment]
I am not handling the migration. 
It is both postresql. The db data is fine. I still have the login and project key. I just lost the git repositories.

**Comment by ramonskie** [comment]
what are the steps you have taken for the upgrade?
because i don't see this behavior

**Comment by ramonskie** [comment]
i have created a dirty hack for now
do not know it this is a pull request worthy 

configuration.rb
```
  execute 'move files' do
    command 'mv /var/atlassian/application-data/stash/shared/* /var/atlassian/application-data/bitbucket/shared/'
    only_if { ::File.directory?('/var/atlassian/application-data/stash/shared/') }
    notifies :delete, 'directory[/var/atlassian/application-data/stash/shared]', :delayed
    notifies :delete, 'execute[chown]'
  end

  execute 'chown' do
    command "chown -R node['stash']['user']:node['stash']['user'] /var/atlassian/application-data/bitbucket/shared/"
    action :nothing
  end

  directory('/var/atlassian/application-data/stash/shared') do
    action :nothing
    notifies :delete, "file[#{node['stash']['home_path']}/shared/stash-config.properties]"
  end
```

**Comment by ramonskie** [comment]
bump

**Comment by linc01n** [comment]
hi @ramonskie 

I would prefer https://github.com/linc01n/chef-stash/commit/14370fa2b0763cd165a8dd87a41e7994e53a927b

what do you think?

**Comment by ramonskie** [comment]
Yes that's much better didn't thought about that one

**Comment by linc01n** [comment]
@ramonskie `4.0.0` finally released! :tada:

**Comment by ramonskie** [comment]
:+1:

**Comment by linc01n** [comment]
Please report bug if you see any problems. Thanks
