### ISSUE TITLE
Incompatibility with Bitbucket 5

### ISSUE THREAD

**Issue by jtusz** [bflad/chef-stash#181]
The current version of this cookbook is incompatible with Bitbucket 5.0 and newer. The last supported version is 4.8.3.

There are some changes within Bitbucket causing problems (e.g. some configuration options are moved from server.xml to bitbucket.properties).
[Bitbucket 5 release notes](https://confluence.atlassian.com/bitbucketserver/bitbucket-server-5-0-release-notes-889528342.html)
[Migrating server.xml to bitbucket.properties](https://confluence.atlassian.com/bitbucketserver/migrate-server-xml-customizations-to-bitbucket-properties-897811761.html)

**Comment by cloneluke** [comment]
I did test the recipe with 4.14.5 (the latest 4.x release of bitbucket) and it does work with that. but yes you are right, it doesnt work with with 5.x mostly because of this:

https://confluence.atlassian.com/bitbucketserver/bitbucket-server-5-0-release-notes-889528342.html

![image](https://user-images.githubusercontent.com/6568361/27228633-0e59cd8a-526e-11e7-83dd-9f0eacf059c5.png)
